name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write  # ✅ Ensure the workflow has write permissions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: your-username
          outputs: |
            github-contribution-grid-snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: github-contribution-grid-snake.svg

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # ✅ Avoids permission issues

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Generate Snake animation" || echo "No changes to commit"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ✅ Uses GitHub token for authentication
